#include "DxLib.h"
#include "Game.h"
#include"enemy.h"
#include"input.h"
#include"Player.h"
#include"shot.h"
#include"Map.h"
#include"Rule.h"
#include"shot.h"
#include"UI.h"
#include"Sound.h"
#include"bitmapText.h"